### ISSUE TITLE
Is this adapter working with the latest version of Sails ? 

### ISSUE THREAD

**Issue by alterx** [azuqua/sails-azuretables#1]
I was thinking about creating my own adapter to use Azure Tables but ran into this one. Is this still being maintained? Does it work with the latest versions of Sails?

**Comment by aembke** [comment]
To be honest I would consider writing your own adapter. We use waterline on its own without sails, so I'm not sure if it's still compatible with the latest version of sails. This one was written about a year ago so it could very well have some incompatibilities. Also, the Azure Tables API is about to drastically change in a very non-backwards compatible way in the coming year and this module uses the old API surface so regardless it's probably best to write a new one against the new API.

**Comment by alterx** [comment]
Wow, that was fast. Thanks for the response.
I'll build my own adapter then. It should be fun.

**Comment by aembke** [comment]
No problem, and good luck. I'd make it a point to target their 0.10.x Azure SDK though, since they're about to deprecate the 0.9.x versions.

**Comment by alterx** [comment]
Yeah, I'll look into that. 
Thanks for the piece of advice
